POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "Dena93@hotmail.com",
    "password":"3E0pMRW7d8O5pmx",
    "firstname":"Aubree",
    "lastname":"Jacobi"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json
Cookie: token rqzgh

{
    "email": "Dena93@hotmail.com",
    "password":"3E0pMRW7d8O5pmx"
}