GET http://localhost:5000/users/

###

POST http://localhost:5000/users/ HTTP/1.1
content-type: application/json

{
    "firstname": "john",
    "lastname": "doe",
    "email":"johndoe@email.com",
    "password":"totoO12@@",
    "confirmPassword":"totoO12@@",
    "birthDate":"2021-06-24T10:51:29.718Z"
}


###

PUT http://localhost:5000/users/a2d9bbe2-2ee3-4e94-9eba-6b35807075af HTTP/1.1
content-type: application/json

{
        "firstname": "julien",
    "lastname": "JOHN",
    "email":"julien_abbz@email.com",
    "password":"totoO12@@",
    "confirmPassword":"totoO12@@",
    "birthDate":"2021-06-24T10:51:29.718Z"
}

###

GET http://localhost:5000/users/a2d9bbe2-2ee3-4e94-9eba-6b35807075af HTTP/1.1

###
GET http://localhost:5000/properties/search/?search=monaco HTTP/1.1