GET http://localhost:5000/users/

###

POST http://localhost:5000/users/ HTTP/1.1
content-type: application/json

{
    "firstname": "julien",
    "lastname": "abbadie",
    "email":"julien_abbadie@email.com",
    "password":"totoO12@@",
    "confirmPassword":"totoO12@@",
    "birthDate":"2021-06-24T10:51:29.718Z"
}

