POST http://localhost:5000/properties/
Content-Type: application/json

{
    "name":"zeiufhz",
    "description":"fizeuyge",
    "type":"SURFCAMP",
    "priceByNight":324234,
    "userId":"224f5b66-c24d-4d1f-bdbb-741a286427f6",
    "addressId":"3708034d-3274-476e-af7a-f0a390da4fb9",
    "phoneNumber":"98365287650"
}


####

GET http://localhost:5000/addresses